name: qubo_embedder
description: An unofficial library to embed and send optimization (QUBO, Ising) problems to DWave System quantum annealing solvers.
version: 0.2.1
homepage: https://github.com/Totemi1324/qubo_embedder

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.1
  ml_linalg: ^13.11.28
  http: ^0.13.5
  binary: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
